#!system/bin/bash
#Author = Mr.F3eLL
#Contact = 081316826548

echo "Sabar Kontol!!!!! "|lolcat
sleep 3
clear
echo "WAITING FOR ME"|lolcat
sleep 2
clear
echo $white"10%"
sleep 1
clear
echo $white"27%"
sleep 1
clear
echo $white"35%"
sleep 1
clear
echo $white"43%"
sleep 1
clear
echo $white"55%"
sleep 1
clear
echo $white"76%"
sleep 1
clear
echo $white"88%"
sleep 1
clear
echo $white"95%"
sleep 3
clear
echo $white"100%"
sleep 1
clear
figlet " DONE!!"|lolcat
sleep 1
clear
figlet -f slant Mr.F3eLL Tamvan |lolcat
echo "_______________________________________________"|lolcat
echo "Author  : Mr.F3eLL"|lolcat
echo "Contact : Mr.F3eLL1603@gmail.com | Facebook : Rafell "|lolcat
echo "Team : BlackHat Hacker Indonesia | Indonesia Hacker Rulez "|lolcat
echo "_______________________________________________"|lolcat

sleep 1

pkg install curl
figlet -f slant Ip Lookup |lolcat
echo "Masukin Domain Target Kalian Mek "|lolcat
echo "Example : grab.github.io"|lolcat
echo "Example : github.io"|lolcat
echo "Masukin Domain Target Kalian Mek "|lolcat
read web
curl https://api.hackertarget.com/reverseiplookup/?q=$web
echo
